### ISSUE TITLE
Small syntax highlighting issue

### ISSUE THREAD

**Issue by dpo** [one-more-minute/Julia-LT#144]
Not a very big deal but the following isn't highlighted correctly:

![screen shot 2014-12-25 at 19 40 33](https://cloud.githubusercontent.com/assets/38760/5555186/ef47390a-8c6d-11e4-9ead-6c78c22fe157.png)

The highlighting is correct if both dots are left out. If that's relevant, I'm using the `base16-dark` theme.

**Comment by denars** [comment]
For me this is a big deal, since the usage of a single transpose operator renders the entire following code as charstring.

In `/js/julia.js` it looks like the transpose operator `.'` is not included in the operator list, but the dot on its own is? This may be the reason why the first apostrophe is recognized as the start of a charstring and the second transpose operator as a dot-character, followed by a closing apostrophe-delimiter.
